//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Softrope")]
[assembly: AssemblyDescription("Sofrope")]
[assembly: AssemblyCompany("http://www.teknohippy.net/")]
[assembly: AssemblyProduct("Softrope")]
[assembly: AssemblyCopyright("Copyright © teknohippy.net 2008")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: AssemblyVersion("0.2.63")]
[assembly: AssemblyFileVersion("0.2.63")]


